# Generated by Django 4.0.5 on 2022-06-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotelinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupant_first_name', models.CharField(max_length=50)),
                ('occupant_last_name', models.CharField(max_length=50)),
                ('occupant_occupation', models.CharField(max_length=50)),
                ('occupant_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('room_number', models.CharField(max_length=20)),
                ('amount_paid', models.FloatField()),
                ('number_of_night', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
