# Generated by Django 4.0.5 on 2022-06-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelinfo',
            name='comment',
        ),
    ]
